apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-pac-xlwi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-pac-xlwi
    app.kubernetes.io/part-of: build-suite-test-application-asup
  name: test-component-pac-xlwi
  namespace: build-e2e-jilo-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-pac-xlwi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-pac-xlwi
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images
        imagePullPolicy: Always
        name: container-image
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
